remote_theme: pages-themes/cayman@v0.2.0
title: Portfolio - Magali Vandenplas
description: Quelques exemples de travaux data issus de mes projets
plugins:
  - jemoji
  - jekyll-remote-theme
  - jekyll-gfm-admonitions
