remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have onetheme: jekyll-theme-minimal
title: Portfolio Magali Vandenplas
description: Quelques exemples de travaux data issus de mes projets
plugins:
  - jemoji
